services:
  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=admin'
      - 'RABBITMQ_DEFAULT_USER=admin'
    ports:
      - '5672:5672'
      - "15672:15672"

  postgres:
    image: 'postgres:15.7'
    environment:
      - 'POSTGRES_DB=tektonvisualizer'
      - 'POSTGRES_PASSWORD=sensemaker'
      - 'POSTGRES_USER=sensemaker'
    ports:
      - '5432:5432'

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - '9092:9092'
      - '9093:9093'